name: deploy-portfolio

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
     
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22.x'

      - name: install dependencies
        run: npm install --legacy-peer-deps

      - name: build project
        run: npm run build

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./dist"
          
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5
